/// GraphQL queries and mutations for Supabase pg_graphql backend
/// Uses collection-style schema generated by pg_graphql extension
library;

class SupabaseProblemQueries {
  /// Fetch all problems with pagination support
  static const String getAllProblems = r'''
    query GetProblems($limit: Int, $offset: Int) {
      problemsCollection(
        first: $limit,
        offset: $offset,
        orderBy: [{ created_at: DescNullsLast }]
      ) {
        edges {
          node {
            id
            owner_id
            title
            description
            difficulty
            category
            geometry_data
            solution
            scalar_constraints
            object_constraints
            scalar_proof
            object_proof
            thumbnail_id
            status
            created_at
            updated_at
          }
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
        }
      }
    }
  ''';

  /// Fetch a specific problem by ID
  static const String getProblemById = r'''
    query GetProblem($id: UUID!) {
      problemsCollection(filter: { id: { eq: $id } }, first: 1) {
        edges {
          node {
            id
            owner_id
            title
            description
            difficulty
            category
            geometry_data
            solution
            scalar_constraints
            object_constraints
            scalar_proof
            object_proof
            thumbnail_id
            status
            created_at
            updated_at
          }
        }
      }
    }
  ''';

  /// Create a new problem record
  static const String createProblem = r'''
    mutation CreateProblem($object: problemsInsertInput!) {
      insertIntoproblemsCollection(objects: [$object]) {
        affectedCount
        records {
          id
          owner_id
          title
          description
          difficulty
          category
          geometry_data
          solution
          scalar_constraints
          object_constraints
          scalar_proof
          object_proof
          thumbnail_id
          status
          created_at
          updated_at
        }
      }
    }
  ''';

  /// Update an existing problem record
  static const String updateProblem = r'''
    mutation UpdateProblem($id: UUID!, $values: problemsUpdateInput!) {
      updateproblemsCollection(
        filter: { id: { eq: $id } },
        set: $values
      ) {
        affectedCount
        records {
          id
          owner_id
          title
          description
          difficulty
          category
          geometry_data
          solution
          scalar_constraints
          object_constraints
          scalar_proof
          object_proof
          thumbnail_id
          status
          created_at
          updated_at
        }
      }
    }
  ''';

  /// Delete a problem by ID
  static const String deleteProblem = r'''
    mutation DeleteProblem($id: UUID!) {
      deleteFromproblemsCollection(filter: { id: { eq: $id } }) {
        affectedCount
        records {
          id
        }
      }
    }
  ''';
}
