/// Validator for command sequences generated by AI
library;

import '../cli/cli.dart';

/// Result of command validation
class ValidationResult {
  final bool isValid;
  final List<String> errors;
  final List<String> warnings;
  final List<Command> validCommands;

  ValidationResult({
    required this.isValid,
    required this.errors,
    required this.warnings,
    required this.validCommands,
  });

  factory ValidationResult.success(List<Command> commands) {
    return ValidationResult(
      isValid: true,
      errors: [],
      warnings: [],
      validCommands: commands,
    );
  }

  factory ValidationResult.failure(List<String> errors) {
    return ValidationResult(
      isValid: false,
      errors: errors,
      warnings: [],
      validCommands: [],
    );
  }

  bool get hasWarnings => warnings.isNotEmpty;
  bool get hasErrors => errors.isNotEmpty;
}

/// Validates command sequences for correctness and dependency satisfaction
class CommandValidator {
  final CommandParser parser;
  
  // Commands that create objects and need labels
  static const _creationCommands = {
    'point',
    'line',
    'segment',
    'circle',
    'midpoint',
    'intersection',
    'triangle',
    'polygon',
    'regular',
    'perpendicular',
    'parallel',
    'perpbisector',
    'bisector',
    'tangent',
    'reflect',
    'rotate',
    'dilate',
    'translate',
  };

  // Commands that reference existing objects
  static const _referenceCommands = {
    'line': 2,        // needs 2 points
    'segment': 2,     // needs 2 points
    'circle': 2,      // needs center and point/radius
    'midpoint': 2,    // needs 2 points
    'intersection': 2, // needs 2 objects
    'triangle': 3,    // needs 3 points
    'perpendicular': 2, // needs line and point
    'parallel': 2,    // needs line and point
    'perpbisector': 2, // needs 2 points
    'bisector': 3,    // needs 3 points
    'tangent': 2,     // needs circle and point
    'reflect': 2,     // needs object and line/point
    'rotate': 3,      // needs object, center, angle
    'dilate': 3,      // needs object, center, factor
    'translate': 2,   // needs object and vector
  };

  CommandValidator({CommandParser? parser}) : parser = parser ?? CommandParser();

  /// Validate a sequence of command strings
  ValidationResult validate(List<String> commandStrings) {
    final errors = <String>[];
    final warnings = <String>[];
    final validCommands = <Command>[];
    final definedLabels = <String>{};

    for (int i = 0; i < commandStrings.length; i++) {
      final cmdString = commandStrings[i];
      final cmdNum = i + 1;

      try {
        // Parse command
        final parsed = parser.parse(cmdString);
        
        if (parsed == null) {
          errors.add('Command $cmdNum: Invalid syntax - "$cmdString"');
          continue;
        }

        // Validate command structure
        final structureError = _validateStructure(parsed, cmdNum);
        if (structureError != null) {
          errors.add(structureError);
          continue;
        }

        // Check dependencies
        final unsatisfied = _checkDependencies(parsed, definedLabels);
        if (unsatisfied.isNotEmpty) {
          errors.add(
            'Command $cmdNum: Undefined references: ${unsatisfied.join(", ")} in "$cmdString"',
          );
          continue;
        }

        // Extract output label(s)
        final outputLabels = _extractOutputLabels(parsed);
        for (final label in outputLabels) {
          if (definedLabels.contains(label)) {
            warnings.add(
              'Command $cmdNum: Label "$label" redefined (previously defined)',
            );
          }
          definedLabels.add(label);
        }

        validCommands.add(parsed);
      } catch (e) {
        errors.add('Command $cmdNum: Exception during validation - $e');
      }
    }

    return ValidationResult(
      isValid: errors.isEmpty,
      errors: errors,
      warnings: warnings,
      validCommands: validCommands,
    );
  }

  /// Validate command structure
  String? _validateStructure(Command command, int cmdNum) {
    final name = command.name.toLowerCase();

    // Check if it's a known command
    if (!_creationCommands.contains(name) && 
        !_referenceCommands.containsKey(name)) {
      return 'Command $cmdNum: Unknown command "$name"';
    }

    // Check minimum argument count
    if (_referenceCommands.containsKey(name)) {
      final minArgs = _referenceCommands[name]!;
      // Add 1 for the label argument
      if (command.arguments.length < minArgs + 1) {
        return 'Command $cmdNum: "$name" requires at least ${minArgs + 1} arguments (got ${command.arguments.length})';
      }
    }

    // Special case: point command needs coordinates
    if (name == 'point') {
      if (command.arguments.length < 3) {
        return 'Command $cmdNum: "point" requires x, y, and label arguments';
      }
      
      // Validate x and y are numeric
      if (command.arguments[0] is! num && command.arguments[0] is! Map) {
        return 'Command $cmdNum: "point" x coordinate must be a number';
      }
      if (command.arguments[1] is! num) {
        return 'Command $cmdNum: "point" y coordinate must be a number';
      }
    }

    return null;
  }

  /// Check if all referenced objects are defined
  List<String> _checkDependencies(Command command, Set<String> definedLabels) {
    final unsatisfied = <String>[];
    
    // All arguments except the last (label) are potential references
    final args = command.arguments;
    if (args.isEmpty) return unsatisfied;

    // Skip the last argument (it's typically the output label)
    for (int i = 0; i < args.length - 1; i++) {
      final arg = args[i];
      
      // Check if argument is a string reference (not a number or coordinate)
      if (arg is String) {
        // Check if it looks like a label (starts with uppercase letter)
        if (RegExp(r'^[A-Z]').hasMatch(arg)) {
          if (!definedLabels.contains(arg)) {
            unsatisfied.add(arg);
          }
        }
      }
    }

    return unsatisfied;
  }

  /// Extract output labels from command
  List<String> _extractOutputLabels(Command command) {
    final args = command.arguments;
    if (args.isEmpty) return [];

    final lastArg = args.last;
    
    // Last argument is typically the label
    if (lastArg is String) {
      // Handle compound labels (e.g., "P1,P2" for intersection)
      if (lastArg.contains(',')) {
        return lastArg.split(',').map((s) => s.trim()).toList();
      }
      return [lastArg];
    }

    return [];
  }

  /// Quick validation for a single command
  bool isValidCommand(String commandString) {
    try {
      final parsed = parser.parse(commandString);
      if (parsed == null) return false;
      
      return _validateStructure(parsed, 0) == null;
    } catch (e) {
      return false;
    }
  }
}
