-- Deprecated migration retained for historical reference.
-- The base schema in problems_schema.sql defines all constraint/proof columns as text.
-- No action required when bootstrapping a fresh environment.
