-- Deprecated migration retained for historical reference.
-- The base schema in problems_schema.sql already creates geometry_data as text.
-- No action required when bootstrapping a fresh environment.