name: frontcalc
description: A mathematical calculator package for parsing and evaluating expressions.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.5
  dartz: ^0.10.1
  
dev_dependencies:
  test: ^1.24.0

# For packages, you don't need to specify flutter as a dependency unless you use Flutter-specific APIs