name: geocalc
description: A mathematical calculator package for parsing and evaluating expressions.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  
dev_dependencies:
  test: ^1.24.0

# Flutter is included for debugPrint support