name: frontpage
description: GeoFront landing page and introduction
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geoapp:
    path: ../geoapp
  designsystem:
    git:
      url: https://github.com/Akash-dvd/geodraw-core.git
      path: packages/designsystem
      ref: main
  google_fonts: ^5.1.0
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
